FROM node:8.9-alpine

ENV NODE_ENV production
ENV FORCE_COLOR 1

RUN apk add --update git

RUN mkdir -p /ck && mkdir -p /app
WORKDIR /app

COPY package.json /ck/
RUN cd /ck && npm install --production
COPY . /ck

RUN ln -s /ck/index.js /usr/local/bin/clientkit

ONBUILD COPY package.json package-lock.* /app/
ONBUILD RUN npm install

ENTRYPOINT ["clientkit"]
