# Config: https://github.com/svg/svgo#what-it-can-do

plugins:
  - cleanupAttrs: true
  - inlineStyles: true
  - removeTitle: true
  - convertPathData: false
  - convertColors:
      shorthex: false
  - minifyStyles: true
