core:
  dist: '{{CWD}}/examples/.dist'
  assetPath: '{{CWD}}/examples'
  mobileFirst: false
colors:
  primary: '#336699'
stylesheets:
  'clientkit.css': '{{CKDIR}}/styles/default.css'
  'tabs.css': '{{CWD}}/examples/tabs/tabs.css'
  'typography.css': '{{CKDIR}}/styles/helpers/typography.css'
  'lists.css': '{{CKDIR}}/styles/helpers/lists.css'
  'grid.css': '{{CKDIR}}/styles/helpers/grid.css'
