#!/bin/bash

NODE_ENV=ghpages node app.js --config conf
cp .dist/clientkit.css .dist/styleguide/clientkit.css
touch .dist/styleguide/.nojekyll
echo "clientkit.io" > .dist/styleguide/CNAME

gh-pages -d .dist --dotfiles
