dist: 'dist'
assetPath: '{{CKDIR}}/styles'
minify: false
tasks:
  preInit:
    - 'updates'
  postInit:
    - 'eslint'
  process:
    - 'scripts'
    - 'stylesheets'
  postProcess:
    - 'hash'

  default:
    - 'preInit'
    - 'initialize'
    - 'postInit'
    - 'process'
  dev:
    -
      - 'preInit'
      - 'initialize'
      - 'postInit'
      - 'process'
    -
      - 'watcher'
  prod:
    - 'preInit'
    - 'initialize'
    - 'postInit'
    - 'process'
    - 'postProcess'
