CKDIR: '{{ENV.TASKKIT_CKDIR}}'
dist: '{{CWD}}/dist'
assetPath: '{{CWD}}/assets'
minify: '{{ENV.MINIFY || ENV.NODE_ENV === "production"}}'
crashOnError: '{{ENV.NODE_ENV === "production"}}'
tasks:
  default:
    -
      - 'clean'
      - 'eslint'
    -
      - 'stylesheets'
      - 'scripts'
      - 'svgsprite'
      - 'styleguide'
  dev:
    - 'clean'
    - 'styleguide'
    - 'watcher'
  prod:
    - 'default'
    - 'hash'
    - 'styleguide'
