dist: 'dist'
assetPath: '{{CKDIR}}/styles'
minify: false
tasks:
  default:
   -
      - 'help'
      - 'initialize'
      - 'eslint'
   -
      - 'stylesheets'
      - 'scripts'
  dev:
    -
      - 'updates'
      - 'initialize'
    -
      - 'watcher'
  # the following tasks are event 'hooks' that you can re-define to customize the
  # processing on your project. 'clientkit-task' is an empty task that does not actually
  # do anything. you can replace it with whatever task(s) you want:
  preInit:
    - 'clientkit-task'
  postInit:
    - 'clientkit-task'
  process:
    - 'clientkit-task'
  postProcess:
    -'clientkit-task'
