dist: '{{CWD}}/dist'
assetPath: '{{CWD}}'
minify: true
tasks:
  default:
    - 'initialize'
    -
      - 'eslint'
      - 'stylesheets'
      - 'scripts'
  dev:
    -
      - 'updates'
      - 'initialize'
    - 'watcher'
  prod:
    - 'default'
    - 'hash'
