dist: '{{CWD}}/dist'
assetPath: '{{CWD}}/assets'
minify: '{{ENV.MINIFY || ENV.NODE_ENV === "production"}}'
crashOnError: '{{ENV.NODE_ENV === "production"}}'
tasks:
  default:
    -
      - 'clean'
      - 'eslint'
    -
      - 'stylesheets'
      - 'scripts'
  dev:
    - 'clean'
    - 'watcher'
  prod:
    - 'default'
    - 'hash'
