dist: '{{CWD}}/dist'
assetPath: '{{CWD}}'
minify: false
#core:
  #urlHashing:
    #active: false
    #jsonMapping: '{{core.dist}}/assets.json'
  #eslint: 'eslint-config-firstandthird'
  #eslintIgnore:
    #- 'node_modules'
    #- '{{core.dist}}'
