dist: 'dist'
assetPath: '{{CKDIR}}/styles'
minify: '{{ENV.MINIFY || ENV.NODE_ENV === "production"}}'
crashOnError: '{{ENV.NODE_ENV === "production"}}'
tasks:
  default:
    -
      - 'initialize'
      - 'eslint'
    -
      - 'stylesheets'
      - 'scripts'
  dev:
    -
      - 'updates'
      - 'initialize'
    - 'watcher'
  prod:
    - 'default'
    - 'hash'
