dist: '{{CWD}}/dist'
assetPath: '{{CWD}}'
minify: true
tasks:
  default:
    - 'initialize'
    -
      - 'eslint'
      - 'stylesheets'
      - 'scripts'
    - 'hash'
    - 'help'
  dev:
    - 'watcher'
