core:
  dist: '{{CWD}}/examples/.dist'
  assetPath: '{{CWD}}/examples'
stylesheets:
  'clientkit.css': '{{CKDIR}}/styles/default.css'
  'tabs.css': '{{CWD}}/examples/tabs/tabs.css'
  'typography.css': '{{CKDIR}}/styles/helpers/typography.css'
