core:
  dist: '{{CWD}}/examples/.dist'
  assetPath: '{{CWD}}/examples'
  mobileFirst: false
  watch:
    css:
      - '{{CKDIR}}/styles/**/*.css'
      - '{{core.assetPath}}/**/*.css'
    yaml:
      - '{{CKDIR}}/conf/*.yaml'
      - '{{CONFIGDIR}}/*.yaml'

siteMaxWidth: '1600px'
colors:
  primary: '#336699'
stylesheets:
  'clientkit.css': '{{CKDIR}}/styles/default.css'
  'tabs.css': '{{CWD}}/examples/tabs/tabs.css'
  'typography.css': '{{CKDIR}}/styles/helpers/typography.css'
  'lists.css': '{{CKDIR}}/styles/helpers/lists.css'
  'mediaqueries.css': '{{CWD}}/examples/mediaqueries/styles.css'
  'grid.css': '{{CWD}}/examples/grid/grid.css'
  'triangle.css': '{{CWD}}/examples/triangles/styles.css'
